### ISSUE TITLE
Issues with rendering 20231104

### ISSUE THREAD

**Issue by liladude** [biblhertz/biblhertz_csl#1]
Hi! a few remarks after today updates:
- remove quotation marks when title is in italics 
 
> Aphthonius, "_Aphthonii Progymnasmata_", Rhetores Graeci, Teubner, Leipzig, vol. 10, 1926
> Aphthonius, _Aphthonii Progymnasmata_, Rhetores Graeci, Teubner, Leipzig, vol. 10, 1926

-  remove extra comma if number of volumes is not set (i.e. one volume) for edited volumes, add space before page span.
>Ottavio Clavuot, "Flavio Biondos ’Italia illustrata’: Porträt und historisch-geographische Legitimation der humanistischen Elite Italiens", in _Diffusion des Humanismus_, ed. Johannes Helmrath, , Ulrich Muhlack, and Gerrit Walther, , Wallstein 2002, pp.55–76.
>Ottavio Clavuot, "Flavio Biondos ’Italia illustrata’: Porträt und historisch-geographische Legitimation der humanistischen Elite Italiens", in _Diffusion des Humanismus_, ed. Johannes Helmrath, Ulrich Muhlack, and Gerrit Walther, , Wallstein 2002, pp. 55–76.
-  remove comma before "and" when more authors or curators exist
>Günther Görz, Chiara Seidl, and Martin Thiering, "Linked biondo: Generating and processing research data based on geographical feature modeling", in _Walking through history. An interdisciplinary approach to Flavio Biondo’s spaces in the ‘Italia Illustrata’_, ed. Tanja Michalsky, and Martin Thiering, , Bibliotheca Hertziana - Max Planck Institute for Art History 2022, https://doi.org/10.48431/hsah.0102 
>Günther Görz, Chiara Seidl, and Martin Thiering, "Linked biondo: Generating and processing research data based on geographical feature modeling", in _Walking through history. An interdisciplinary approach to Flavio Biondo’s spaces in the ‘Italia Illustrata’_, ed. Tanja Michalsky and Martin Thiering, Bibliotheca Hertziana - Max Planck Institute for Art History 2022, https://doi.org/10.48431/hsah.0102

**Comment by hawkenbury** [comment]
OK - I think that I have fixed these issues
Have added a comma after the title
